@startuml kundenverwaltungssystem

abstract class person{
    - id : int
    - name : String
    - strasse : String
    - hausnummer : String
    - ort : String
    - plz : String
    - anzahlBestellungen : int
    - bisherigesBestellvolumen : double
    {abstract} istPremiumkunde() : boolean
    {abstract} ermittleWichtigkeit() : double
    {abstract} datenAusgeben() : void
    + lieferePostanschrift() : String
    + ergaenzeBestellung(double bestellwert) : void
    + getId() : int
    + getName() : String
    + getStrasse() : String
    + getHausnummer() : String
    + getOrt() : String
    + getPlz() : String
    + getAnzahlBestellungen() : int
    + getBisherigsBestellvolumen() : double
}

class natuerlichePerson extends person{
    - anrede : String
    - geschlecht : char
    + bestellungZurueckgeben() : void
    + istPremiumkunde() : boolean
    + ermittleWichtigkeit() : double
    + datenAusgeben() : void
    + getAnrede() : String
    + getGeschlecht() : char
}

class juristischePerson extends person{
    - rechtsform : String
    - istKapitalgesellschaft : boolean
    + istPremiumkunde() : boolean
    + ermittleWichtigkeit() : double
    + lieferePostanschrift() : String
    + datenAusgeben() : void
    + getRechtsform() : String
    + getIstKapitalgesellschaft() : boolean
}

@enduml