@startuml kundenverwaltungssystem

abstract class person{
    - name : String
    - strasse : String
    - ort : String
    - plz : String
    - anzahlBestellungen : int
    - bisherigesBestellvolumen : double
    {abstract} istPremiumkunde() : boolean
    + lieferePostanschrift() : String
    + ergaenzeBestellung(double bestellwert) : void
    {abstract} ermittleWichtigkeit() : double
}

class natuerlichePerson extends person{
    - anrede : String
    - geschlecht : String
    {private} bestellungZurueckgeben() : void
}

class juristischePerson extends person{
    - rechtform : String
    - istKapitalgesellschaft : boolean
}

@enduml