@startuml kundenverwaltungssystem

abstract class person{
    - name : String
    - strasse : String
    - hausnummer : String
    - ort : String
    - plz : String
    - anzahlBestellungen : int
    - bisherigesBestellvolumen : double
    {abstract} istPremiumkunde() : boolean
    + lieferePostanschrift() : String
    + ergaenzeBestellung(double bestellwert) : void
    {abstract} ermittleWichtigkeit() : double
    + getName() : String
    + getStrasse() : String
    + getHausnummer() : String
    + getOrt() : String
    + getPlz() : String
    + getAnzahlBestellungen() : int
    + getBisherigsBestellvolumen() : double
}

class natuerlichePerson extends person{
    - anrede : String
    - geschlecht : String
    + bestellungZurueckgeben() : void
    + istPremiumkunde() : boolean
    + ermittleWichtigkeit() : boolean
}

class juristischePerson extends person{
    - rechtsform : String
    - istKapitalgesellschaft : boolean
    + istPremiumkunde() : boolean
    + ermittleWichtigkeit() : double
    + lieferePostanschrift() : String
}

@enduml